### ISSUE TITLE
can't find pretty-formula.jar

### ISSUE THREAD

**Issue by TrueV** [mzur/pretty-formula#1]
Hey there,
I am currently trying to get your code running, though I can't find the jar file anywhere.
Maybe I missed something.

**Comment by mzur** [comment]
It's in the ZIP file you can download from the [releases page](https://github.com/mzur/pretty-formula/releases/tag/v1.0.0).

**Comment by TrueV** [comment]
Thanks, found it, though I somehow can't get the library running in my android project. Do you have experiences with that? - Could it be that the jdk I use is not fitting (1.8.x) (Can't get a prior version from oracle...)

**Comment by mzur** [comment]
I'm pretty sure I developed it using JDK 8 since I used [streams](https://github.com/mzur/pretty-formula/blob/master/src/de/uni_bielefeld/cebitec/mzurowie/pretty_formula/main/VanesaFormulaParseRules.java#L157). Does it throw any helpful errors if you try to run it?

**Comment by TrueV** [comment]
I tried building the project with jdk1.7 and 1.8, but the error was still the same. Maybe I'm doing something wrong, I am not very experienced with using external libs in my projects.

![error1](https://cloud.githubusercontent.com/assets/15327624/13547484/6349bfc6-e2d5-11e5-8f46-aa50d731c83f.PNG)

Currently, I am using pretty-formula.jar and antlr-runtime-4.4.jar (Because there was a dependency in pretty-formular.jar to use a "ParseException" class, that referred to that library. 

> Error:com.android.dx.cf.iface.ParseException: **bad class file magic** (cafebabe) or version (0034.0000)
>   at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)
>   at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
>   at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)
>   at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)
>   at com.android.dx.command.dexer.Main.parseClass(Main.java:764)
>   at com.android.dx.command.dexer.Main.access$1500(Main.java:85)
>   at com.android.dx.command.dexer.Main$ClassParserTask.call(Main.java:1684)
>   at com.android.dx.command.dexer.Main.processClass(Main.java:749)
>   ... 12 more
> 1 error; aborting
> Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> 
> > com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_73\bin\java.exe'' finished with non-zero exit value 1

**Comment by mzur** [comment]
You need _all_ libraries of the [lib directory](https://github.com/mzur/pretty-formula/tree/master/lib).

**Comment by TrueV** [comment]
Sorry didn't read that properly. Now I added all libraries but the outcome is not different so far. :/
Still the same Error-Log. (All libraries are added now)
![error2](https://cloud.githubusercontent.com/assets/15327624/13547800/334663b4-e2e0-11e5-962c-b6f2a19e6d3e.PNG)

It is no problem to run the pretty-formular.jar on its own, which shows the GUI, but I just want to use the methods in an android application, and the gradle somehow can't get it running. ;-)

**Comment by mzur** [comment]
I'm afraid my competence stops here as well, sorry :confused: I don't have much experience in building Android applications like this. Maybe you try posting a question on StackOverflow?

**Comment by zhumingu** [comment]
Maybe you could look at here[https://github.com/lokedhs/jlatexmath-android](url).of course,pretty-formula is very good.thanks @mzur .I just hope you save  time.u can also see [http://www.forkosh.com/mathtex.html](url)(base on server) and [https://www.mathjax.org/](url)(base on js).
