### ISSUE TITLE
About Reverse Conversion

### ISSUE THREAD

**Issue by lone7dehao** [mzur/pretty-formula#2]
First of all, thank you for providing this excellent project. 
Can you provide a latex expression conversion formula

**Comment by mzur** [comment]
Can you please elaborate? Do you want to create an image directly from LaTeX instead of the simple text formula?

**Comment by lone7dehao** [comment]
Sorry, my description was not accurate enough.
e.g.
I have expression LaTex, \left(\frac{{a}_{1}}{{\left({b}_{1}+\sqrt{c}\right)}^{2}}\right)+\sin{\left({a}_{2}\cdot {b}_{2}\right)}.
I want original formula, (a_1 / (b_1 + sqrt(c))^2) + sin(a_2 * b_2)
The scene has already recognized the Latex expression, and we hope it can be translated into a computable expression

**Comment by mzur** [comment]
I'm sorry but this is an entirely different task compared to what this package is about. Either you implement this from scratch or you find an existing LaTeX parser that can do something like this.
